### PR TITLE
Sign-Up Page for New Users

### PR DESCRIPTION
**Pull request by saivittalb**
Perfectly implemented Sign-Up page for new users 🎉

To test this feature, run the project locally using ```ng serve``` and then change the address to ```localhost:4200/signup```

I have used @sidhyatikku new Sign-Up wireframe and also modified it such as removed Sign-In button beside Sign-Up when user registers and also removed user icon at the top right corner so as the user registers with ease as he/she still doesn't have an account to show his profile details on clicking that user icon. Also added a Javascript function named Validate() to ensure the "password" and "confirm password" sections match.

Preview of the Login Page👇

screen shot 2018-11-18 at 3 23 43 pm

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Submit your task for approval if not done already

**Comment by saivittalb** [comment]
Hmm... this isn’t a task yet! I just worked on it because I completed login UI recently and thought it would be also good to come up with signup UI....

Okay, I will try to fit the width into one screen 👍

**Comment by saivittalb** [comment]
@nikitadhiman Hey, I found out that the zoomed in effect is due to my default built-in Viewport settings and it has nothing to do with the code. And I tried changing the CSS file but it isn't changing much. The view is automatically getting adjusted to default Viewport settings. On remaining computers, the view is just in a single page without making the user to scroll. I can change the viewport to some constant view in the HTML file but if I do, maybe the view on everyone's computer(except mine) might be so small.

**Comment by nikitadhiman** [comment]
Did you try using height:90vh .... something like that and disable scroll

**Comment by saivittalb** [comment]
> Did you try using height:90vh .... something like that and disable scroll

Nah... I just reduced the logo size and the problem is solved! 🎉

**Comment by nikitadhiman** [comment]
@saivittalb , merging this but would be removing all unnecessary changes

**Pull request merged**
