### PR TITLE
Login Page for Registered Users

### PR DESCRIPTION
**Pull request by tavleensasan**
Login Page for registered users!
Task: https://codein.withgoogle.com/dashboard/task-instances/6445681100193792/

Screenshot:
certificate generator

A new responsive login page for users.

### CODE REVIEW

**Comment by tavleensasan** [comment]
Another login page for this task is

jboss 1

**Comment by prateekiiest** [comment]
Please squash all the commits into one

**Comment by nikitadhiman** [comment]
I agree, the tasks asks the design to be coded in HTML CSS but for it to be merged in actual project it definitely have to follow angular standards. There's no issue with HTML CSS code and as far as I am aware only two instances of this task have been approved and yes they were sent for more work initially because they too didn't followed angular standard. 

It's not hard, not much work is required. Just place your HTML code in basic.component.html and css code in basic.component.css

**Comment by tavleensasan** [comment]
Actually I'm new to Angular and I'm trying my best to understand it. But it definitely will take time.
So I presented the code in HTML and CSS :)

**Comment by nikitadhiman** [comment]
Hi, thanks for efforts. Will be glad to reopen this when the requested changes are made

**Pull request closed without merging**
