### PR TITLE
Login page for Jboss certificate generator

### PR DESCRIPTION
**Pull request by iraiyer**
Hello ,Good Day !
                         I am a participant of GCI 2018 and this is the login page for certificate generator for Jboss , as the login page was to be designed according to the wireframe so, I did the same and here is the preview of the page , hope you like it !
Thank You !
screenshot 10

### CODE REVIEW

**Comment by iraiyer** [comment]
Hello ! thank you for welcoming and helping me in my first pull request , sure I will do that .....

**Comment by iraiyer** [comment]
hello , I introduced some padding to the box is this right? so that I can squash my commits

**Comment by nikitadhiman** [comment]
That's correct

**Comment by iraiyer** [comment]
can you help me with squashing your commits ?

**Comment by nikitadhiman** [comment]
Please refer this, https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by iraiyer** [comment]
sorry I just can't seem to squash my commits !  I have tried every way possible !

**Comment by nikitadhiman** [comment]
No issues, submit your task for approval if not done already. Thanks for your efforts

**Pull request closed without merging**
