### PR TITLE
Integration of Backend Service

### PR DESCRIPTION
**Pull request by saivittalb**
Perfectly integrated backend service 🎉

To test this feature, run the project locally using ```ng serve``` and then change the address to ```localhost:4200/login``` and also please connect the ```Certificate Front Server URL``` to the ```baseURL``` in ```environment.ts``` file.

Check out the testing preview [here](https://youtu.be/hXyG9Gla8Qk) 👈

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Hi, thanks for your work. Please give me sometime to check your work. Thanks

**Comment by saivittalb** [comment]
Hey, I have added the testing video link in the description... Please check! Also, for any mashups and to avoid confusion, I will once again push the changes!

**Comment by nikitadhiman** [comment]
@saivittalb please resolve the conflicts. This being considered for merge.

**Comment by saivittalb** [comment]
Done 👍

**Comment by nikitadhiman** [comment]
great Job, this has been partially merged

**Pull request closed without merging**
