### PR TITLE
Add login UI

### PR DESCRIPTION
**Pull request by junron**
[Task](https://codein.withgoogle.com/dashboard/task-instances/6270335772000256/)

Added login UI based on wireframe, with some modifications.

I did not include the `SIGN UP` button as the signup page may need other information such as email address and may it not be suitable to put both on the same page.

I will add Navbars and footers soon
Mobile:
localhost_4200_login nexus 5x

Desktop:
localhost_4200_login

### CODE REVIEW

**Comment by junron** [comment]
Oops didn't realise navbars are part of the task

**Comment by nikitadhiman** [comment]
> Oops didn't realise navbars are part of the task

for login page, no! but yes we would need footer. I included navbar too as you mentioned you'll be working on it soon

**Comment by junron** [comment]
I'll do both together anyway

**Comment by junron** [comment]
Added footer and navbar

Mobile
localhost_4200_login nexus 5x 1

Desktop:
localhost_4200_login 2

**Comment by nikitadhiman** [comment]
@junron and yes don't forget to squash your commits

**Comment by junron** [comment]
Squashed and rebased

**Comment by nikitadhiman** [comment]
> Squashed and rebased

awesome

**Pull request closed without merging**
