### PR TITLE
Navbar implementation & Login function using Firebase

### PR DESCRIPTION
**Pull request by Khukhuna**
**Part of GCI** :tada: :balloon: 

Added new navbar component & added basic login page.

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Also, great job.

**Comment by Khukhuna** [comment]
Yeah :joy: It looks like a big change but in reality:

**angular.json** - added font awesome in styles
**package.json** - decreased verison of bootstrap to 3.3.7 & added font-awesome
**app.component.html** - added navbar component
**app.module.ts** - angular automatically added navbar component in declarations
**login.component.html** - login ui update
& auto generated navbar components

**Comment by Khukhuna** [comment]
Added firebase authentication funcionality to this login form.

[Video preview](https://www.youtube.com/watch?v=DplMoIgEltc)
image

**Comment by nikitadhiman** [comment]
closing this for now.

**Pull request closed without merging**
