### PR TITLE
Added new icon design

### PR DESCRIPTION
**Pull request by HarshHC**
Task : https://codein.withgoogle.com/dashboard/task-instances/5612278016638976/

High res icon:
web_hi_res_512

Android icon(all dpi's) : 
[ic_launcher.zip](https://github.com/JBossOutreach/certificate-generator-front/files/2518951/ic_launcher.zip)

### CODE REVIEW

**Comment by the-dagger** [comment]
Whoa looks good @HarshHC. 💯
One nit, right now the certificate icon is stuck to the bottom, try leaving some space between the image and the edges :)

**Comment by HarshHC** [comment]
Updated @the-dagger heres the new icon high res image:
web_hi_res_512
 @nikitadhiman THanks. the tool i used: www.desygner.com

**Comment by the-dagger** [comment]
Looks good! 💯

**Comment by HarshHC** [comment]
signup_page

**Pull request closed without merging**
