### PR TITLE
GCI'18 Task, made logo for certificate-generator

### PR DESCRIPTION
**Pull request by crowded-geek**
The folder and files of logo are in src/assets folder 💯 👀 
### Edit: Here are the 6 images in description:

- mdpi
certificate_gen

- hdpi
certificate_gen

- xhdpi
certificate_gen

- xxhdpi
certificate_gen

- xxxhdpi
certificate_gen

- web_hi_res_512x512
web_hi_res_512

### CODE REVIEW

**Comment by crowded-geek** [comment]
@nikitadhiman Done, added them in description :)

**Comment by nikitadhiman** [comment]
Also, one genuine feedback.. by having first look at the logo I cannot understand as a new user what it is about. Can you work on that part? By looking at logo itself people should get a basic idea about the portal

**Comment by crowded-geek** [comment]
Sure, I guess a tagline should do the work

**Comment by crowded-geek** [comment]
btw it isn't a good practice for a logo/favicon to contain much text. does Google's logo depict that it's a search engine?

**Comment by crowded-geek** [comment]
is it good now?

**Comment by divyanshu-rawat** [comment]
@nikitadhiman is right, logo must depict on first look what it is all about, to your google logo question please read every logo out there has some hidden meaning associated with it [this](https://www.businessinsider.in/See-The-Hidden-Meanings-Inside-17-Tech-Company-Logos/articleshow/36692056.cms)

**Comment by crowded-geek** [comment]
Actually i am not that good with graphic designing, i thought for starters this logo could help

**Comment by nikitadhiman** [comment]
This is a good efforts thou... Why the spikes in the logo?

**Comment by crowded-geek** [comment]
You know, like there are spikes in badges

**Comment by nikitadhiman** [comment]
Cool, great efforts

**Comment by nikitadhiman** [comment]
yup, also closing this for now

**Pull request closed without merging**
