### PR TITLE
wireframe for student and issuer dashboard

### PR DESCRIPTION
**Pull request by Ananthavijay**
Task links - https://codein.withgoogle.com/dashboard/task-instances/6601558469902336/
https://codein.withgoogle.com/dashboard/task-instances/6546330492076032/

- This was done with figma.
- Matches material guidelines

These are the added file :

student dashboard

issuer dashboard

Thanks

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Heart is just to like them..Yes will remove the edit option

**Comment by divyanshu-rawat** [comment]
@Ananthavijay yes but do you think student will like his/her own certificates and delete them as well? Why should anyone will delete certificates assign to them?

**Comment by Ananthavijay** [comment]
yep I was thinking of it now @divyanshu-rawat . Will change and update it within a min

**Comment by divyanshu-rawat** [comment]
@Ananthavijay sure 👍

**Comment by Ananthavijay** [comment]
Can i add ``date``for the certificates in students dashboard?

**Comment by divyanshu-rawat** [comment]
I think date should be written in the certificate itself on which date it is assigned makes sense right? but if you want you can add.

**Comment by Ananthavijay** [comment]
is this okay @divyanshu-rawat ?
student dashboard

**Comment by divyanshu-rawat** [comment]
for student this seem fine to me @Ananthavijay 👍

**Comment by divyanshu-rawat** [comment]
And for Mentor @Ananthavijay purpose of having star?

**Comment by Ananthavijay** [comment]
let me align the buttons properly and squash the commits.
Pls check the issuer's dashboard also
Thanks

**Comment by divyanshu-rawat** [comment]
Yes for Issuer purpose of having star?

**Comment by Ananthavijay** [comment]
sorry will remove it

**Comment by nikitadhiman** [comment]
LGTM

**Comment by nikitadhiman** [comment]
Thanks for your efforts

**Comment by divyanshu-rawat** [comment]
maybe instead of star you can write date in it's place? and it would be great if instead of writing date if you write it in a format like 11/12/2018 etc.

**Comment by divyanshu-rawat** [comment]
@nikitadhiman please wait some changes are still needed to be done.

**Comment by Ananthavijay** [comment]
yep @nikitadhiman Pls dont credit me all the credit goes to @divyanshu-rawat

**Comment by divyanshu-rawat** [comment]
It's fone @Ananthavijay please do some modification and update the PR.
Then I will be happy to merge this 👍 😃

**Comment by divyanshu-rawat** [comment]
@Ananthavijay , @nikitadhiman has already approved the task, although feel free to update the PR 👍

**Comment by Ananthavijay** [comment]
oh k

**Comment by Ananthavijay** [comment]
done @divyanshu-rawat

**Comment by Ananthavijay** [comment]
check this also https://codein.withgoogle.com/dashboard/task-instances/6546330492076032/

**Comment by divyanshu-rawat** [comment]
@nikitadhiman are these tasks same? https://codein.withgoogle.com/dashboard/task-instances/6546330492076032/

**Comment by Ananthavijay** [comment]
Actually it's not the same.
One task is for creating dashboard design for issuer
And another is for creating dashboard design for student
I made both in the same PR @divyanhu-rawat

**Comment by divyanshu-rawat** [comment]
Sure I will apporve @Ananthavijay 👍

**Comment by Ananthavijay** [comment]
Thanks for all the help and spending your valuable time with me @divyanshu-rawat

**Comment by divyanshu-rawat** [comment]
Welcome @Ananthavijay 👍

**Comment by nikitadhiman** [comment]
@Ananthavijay it is actually you integrating feedbacks so quickly and hence approved it.... Also there are different tasks for both the wireframes. @divyanshu-rawat  thanks for coordinating on this

**Comment by Ananthavijay** [comment]
@divyanshu-rawat @nikitadhiman 
Which is nice. With outline or without outline(for buttons) ? 
screenshot 5

**Comment by nikitadhiman** [comment]
With outline..... They actually feel like buttons, else seems like plain links

**Comment by nikitadhiman** [comment]
closing this for now

**Pull request closed without merging**
