### PR TITLE
Made sign up and sign in page look alike

### PR DESCRIPTION
**Pull request by Ananthavijay**
Check by changing each `[ ]` to `[x]` Please take note of the white-space as it matters.

- This Pull request
   - [X] Fixes a bug.
   - [ ] Implements a new feature.
- [X] I have read the **[CONTRIBUTING.md]** .

- [X] I have included a description of changes below.
- [X] I have included screenshots  showing before and after the changes were made.
- [X] I have squashed the commits **(mandatory)**.

## Description / Changes

- Fixes https://github.com/JBossOutreach/certificate-generator-front/issues/262

- Check the online deployment here : https://ananthavijay.github.io/certificate-generator-front/

### CODE REVIEW

**Review by nikitadhiman — COMMENTED** [review]
Thanks for your work, will review this soon

**Comment by Ananthavijay** [comment]
@nikitadhiman Thanks and sorry for the delay 😄

**Review by prithaupadhyay — CHANGES_REQUESTED** [review]
@Ananthavijay Good Work. Just give a small margin in the bottom too.
image
There should be a small margin between the sign up button and the footer.

**Comment by Ananthavijay** [comment]
will do it right away @prithaupadhyay

**Comment by Ananthavijay** [comment]
Check it now. I will squash the commits when the PR is approved

**Comment by prithaupadhyay** [comment]
@Ananthavijay The changes have not been reflected in the online deployment submitted by you. Make the changes and I'll review it.

**Comment by Ananthavijay** [comment]
@prithaupadhyay  I made the commit it will take some 3 more mins to change 😄

**Comment by prithaupadhyay** [comment]
@Ananthavijay Okay. I'll check.

**Comment by prithaupadhyay** [comment]
@Ananthavijay Great work. Just give some margin between the main wrapper for sign in and the footer. Do make the changes both in sign up and sign in section. Else, looks perfect.

**Comment by Ananthavijay** [comment]
Will do it right away

**Review by nikitadhiman — COMMENTED** [review]
Hi, can you attach latest  work's screenshot please

**Comment by Ananthavijay** [comment]
Yep just a sec

**Comment by Ananthavijay** [comment]
Login page : 

screenshot 114

screenshot 115

Sign up page:

screenshot 116
screenshot 117

**Review by prithaupadhyay — APPROVED** [review]
Great Work @Ananthavijay . I'll merge it after testing.

**Review by nikitadhiman — COMMENTED** [review]
Just a minor thing, I guess margin at the bottom should be same as margin on top and yes do check for the responsiveness

**Comment by prithaupadhyay** [comment]
@Ananthavijay Please make the changes as said by Nikita. Also, please make the margin same in both sign up and sign in pages.

**Comment by Ananthavijay** [comment]
Yep will do it by tmrw cause having exams

**Review by prithaupadhyay — APPROVED** [review]
LGTM 🎉🎉

**Pull request merged**
