### PR TITLE
Login.component.html

### PR DESCRIPTION
**Pull request by Guneet06**

### CODE REVIEW

**Comment by Guneet06** [comment]
Please review

**Comment by Guneet06** [comment]
jboss

**Comment by Guneet06** [comment]
Output

**Comment by Guneet06** [comment]
Ab wapis dala hai

**Comment by Guneet06** [comment]
<html>
<head>
	<title> J Boss </title>
<link href="indexcss.css" rel="stylesheet">
 
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

</head>
<body>
	<div class="log">
	<body background="images/bg-01.jpg">
 <center>
	
</center>
 <div class="login-page">
<div class="form">
<form class="register-form">
 

 <div ng-app="">
   Username <input type="username" name="user" ng-model="user"
type="username" placeholder="username"/>
   Password <input type="password" name="per" ng-model="par"
type="password" placeholder="password"/>
 Email Id<input name="myInput" ng-model="myInput" type="email"
ng-model="email" placeholder="email id" />
 <button ng-click="">Create</button>
</div>

</div>
</div>
</form>
      
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="www.twitter.com">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="www.facebook.com">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="www.github.com">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; JBoss Community 2018</p>
          </div>
        </div>
      </div>
    </footer>
<script src="bootstrap/js/jquery.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
 
 </div>
</body>
</html>

**Comment by nikitadhiman** [comment]
If you see files changed....it shows only one file.... Ideally there should be 2 files with changes. Please make the needed change

**Comment by Guneet06** [comment]
Yes there are two files

**Comment by Guneet06** [comment]
Login.component.html and login.component.css

**Comment by Guneet06** [comment]
Didi please review this task and approve it

**Comment by Guneet06** [comment]
I tried my level best

**Comment by nikitadhiman** [comment]
I can see just one file here https://github.com/JBossOutreach/certificate-generator-front/pull/134/files

**Comment by Guneet06** [comment]
Please didi

**Comment by Guneet06** [comment]
Mujhe nai file dalni nahi aati

**Comment by Guneet06** [comment]
Commits me check karo

**Comment by Guneet06** [comment]
https://github.com/JBossOutreach/certificate-generator-front/pull/135/files

**Comment by Guneet06** [comment]
Its another pull request

**Comment by nikitadhiman** [comment]
Alright! Will have a look. Don't worry, here to help

**Pull request closed without merging**
