### PR TITLE
Basic Certificate Template

### PR DESCRIPTION
**Pull request by ant159**
Task: https://codein.withgoogle.com/tasks/5438479950413824/?sp-is_beginner=False&sp-search=basic%20cer
@nikitadhiman Is it okay?
basic-temp2

### CODE REVIEW

**Comment by ant159** [comment]
@nikitadhiman I hope this is better. I changed the screenshot in the description...

**Comment by prithaupadhyay** [comment]
@ant159  We are considering your PR for merge. Please have a look at the other merged Certificate templates. There is a folder named as templates inside the app folder. Inside that templates folder, you need to create a separate folder for your template. That folder should contain all the files ____.component.css, ____.component.html, ______.component.spec.ts, and _____.component.ts. 
Please make the changes asap, so that we can merge it.

**Comment by prithaupadhyay** [comment]
@ant159  Please change the folder name from templates to something like certificate-template-ant or something else but unique. Else looks good to me.

**Comment by ant159** [comment]
@prithaupadhyay  Done.

**Comment by prithaupadhyay** [comment]
@ant159 Good work. Just squash your commits and we'll be done.

**Pull request merged**
