### PR TITLE
Update angular.json

### PR DESCRIPTION
**Pull request by pranavgade20**
correct some typos
Link to GCI task: https://codein.withgoogle.com/dashboard/task-instances/5003521431699456/

### CODE REVIEW

**Comment by divyanshkul** [comment]
**Mentor Note**: Student put a lot of effort into this, this PR should be merged

**Comment by divyanshkul** [comment]
@pranavgade20 remember to squash your commits from next time

**Comment by divyanshkul** [comment]
Mentor Note: Student put a lot of effort into this, this PR should be merged

**Comment by divyanshkul** [comment]
**Mentor Note:** Student put a lot of effort into this, this PR should be merged

**Comment by nikitadhiman** [comment]
Merging this, we can move to next tasks.

**Comment by nikitadhiman** [comment]
@pranavgade20, Some of the tasks available for certificate generator frontend: 

Task for basic template creation :
https://codein.withgoogle.com/dashboard/tasks/5438479950413824/
Task for registering certificate issuer:
https://codein.withgoogle.com/dashboard/tasks/6194406089555968/
Task for adding optional fields in the certificate: https://codein.withgoogle.com/dashboard/tasks/5380860145565696/
Template validations: https://codein.withgoogle.com/dashboard/tasks/5069677484048384/
Certificate preview for organization : https://codein.withgoogle.com/dashboard/tasks/4908702931877888/
Task for bulk upload for certificate generation : https://codein.withgoogle.com/dashboard/tasks/5159926088335360/
Dashboard or landing page for certificate issuers : https://codein.withgoogle.com/dashboard/tasks/4635616965820416/
Task for the list of certificates for the organization, feature of the dashboard: https://codein.withgoogle.com/dashboard/tasks/6434868071235584/
Editing single certificate before issue: https://codein.withgoogle.com/dashboard/tasks/5596181167079424/
Task to generate single certificate: https://codein.withgoogle.com/dashboard/tasks/6330113097465856/
Angular authentication guards for the project: https://codein.withgoogle.com/dashboard/tasks/6306502907265024/
Task for login page for already existing users: https://codein.withgoogle.com/dashboard/tasks/6159082248470528/

**Pull request merged**
