### PR TITLE
Added Feature for Generating Certificates

### PR DESCRIPTION
**Pull request by saivittalb**
Perfectly implemented feature for Generating Certificates 🎉

To test this feature, run the project locally using ```ng serve``` and then change the address to ```localhost:4200/generator```

Check out the testing preview [here](https://youtu.be/SURfVcADi1A) 👈

### CODE REVIEW

**Comment by saivittalb** [comment]
> @saivittalb Great work 🎉. Just squash your commits. Else looks good to me.
> @nikitadhiman Please have a look.

Actually, I don't know how to squash merge commits when I update my branch! 😅

**Comment by nikitadhiman** [comment]
Awesome work!

**Comment by nikitadhiman** [comment]
I would suggest that ID should not be a part of the form field but it would be generated at the backend

**Comment by saivittalb** [comment]
> I would suggest that ID should not be a part of the form field but it would be generated at the backend

Hey @nikitadhiman, I have removed the ID Field and also added screenshot preview here - https://github.com/JBossOutreach/certificate-generator-front/pull/159

I'm closing this PR because this is messed up pretty much! Thanks!

**Pull request closed without merging**
