### PR TITLE
Footer & Social links

### PR DESCRIPTION
**Pull request by Khukhuna**
Part of GCI 18 :tada: :balloon: [**Task**](https://codein.withgoogle.com/dashboard/task-instances/4825714885918720/)
## Web
ui

### CODE REVIEW

**Comment by Khukhuna** [comment]
Full web image was too big for description, That's why I added mobile screenshot :joy:
I'll update pr description with Webview Screenshot in a sec. Thank you.

P.S. Happy Halloween :jack_o_lantern:

**Comment by nikitadhiman** [comment]
Happy halloween to you too! Great Job, looking forward to have more contributions from you :) Best of luck

**Comment by Khukhuna** [comment]
Thank you :ghost: 
Yes, I submitted task yesterday :smile: I'm waiting for review on another task right now and then I'll work on sidenavbar.

Is it oky to add navbar component in this branch? To be sure that footer and SideNavbar looks good together? :nerd_face:

**Comment by nikitadhiman** [comment]
sure go ahead!

**Comment by nikitadhiman** [comment]
@Khukhuna, hope you are doing great. Your work is being considered for merge. Please do a minor change and remove up arrow as seen on right side as this is a single screen we won't need this. Thanks

**Pull request closed without merging**
