### PR TITLE
Wireframe - Login

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Wireframe for Login Page
* Made this PR in reference to #85 
* [View Repo](https://github.com/sidhyatikku/certificate-generator-front/tree/loginfram)

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@nikitadhiman Please review the PR

**Comment by Ananthavijay** [comment]
@nikitadhiman @sidhyatikku Instead of the tile ``certificate generator`` we can use ``Welcome back``
It may look good

**Comment by nikitadhiman** [comment]
Merging this and making some changes myself as @sidhyatikku seems to unavailable for time being

**Comment by sidhyatikku** [comment]
Sorry for being late, I was not in home 😁

**Pull request merged**
