### PR TITLE
Navbar UI & Login/Signup Feature

### PR DESCRIPTION
**Pull request by jamesnoonan**
GCI 💻 
Created a navbar compenent and added left-aligned vertical navbar
image

### CODE REVIEW

**Comment by nikitadhiman** [comment]
exactly, there's no need of signin/signup once the user is inside the application

**Comment by nikitadhiman** [comment]
also, above table we would need buttons saying generate single certificate and bulk upload....

**Comment by jamesnoonan** [comment]
I think that is another task. I will add that once I have finished the navbar task. What would you like me to change on the navbar?

**Comment by nikitadhiman** [comment]
> I think that is another task. I will add that once I have finished the navbar task. What would you like me to change on the navbar?

That's right... but you can include that in navigation bar too...just a suggestion. Great work thou

**Comment by dilum1995** [comment]
@jamesnoonan 

As one of our mentors(@nikitadhiman ) has mentioned before, please concern about following requirements and make the changes accordingly,

- exactly, there's no need of signin/signup once the user is inside the application (once user reach this screen).
- we would need buttons saying generate single certificate and bulk upload.

So, please work on these and submit your final work according to the submissions requirements.

**Comment by jamesnoonan** [comment]
Ok I will add these features and resubmit

**Comment by nikitadhiman** [comment]
> Ok I will add these features and resubmit

I feel the appropriate placement for these buttons would be navbar as we move ahead in project we would have operations on certificates (buttons) available based on user roles. Again this would be an addition wrt this task. Thanks for your time and efforts @jamesnoonan

**Comment by jamesnoonan** [comment]
I have updated the UI to make it easier to use. My project is not connected to firebase at the moment, so the switch between the login/logout is simply controlled by a variable. Angular Material has been added.
image
Is this where the buttons should go? I assumed they would go near the list of certificates. Also, I wasn't sure how the table fit into the system so we might need to change it.

**Comment by nikitadhiman** [comment]
Buttons should be on top, because list can be long.

**Comment by jamesnoonan** [comment]
Are there any other changes I should make?
image

**Comment by nikitadhiman** [comment]
> Are there any other changes I should make?
> image

no, this is great! Thanks for your efforts and patience :+1:

**Comment by nikitadhiman** [comment]
Please submit task for review, will approve

**Comment by jamesnoonan** [comment]
Added Firebase login and signup with error messages
login
signup
Navigation buttons are hidden from unauthenticated users

**Comment by nikitadhiman** [comment]
Closing this for now

**Pull request closed without merging**
