### PR TITLE
Added Responsive Certificate Template for Optional Fields

### PR DESCRIPTION
**Pull request by saivittalb**
Perfectly added Responsive Certificate Template for Optional Fields 🎉

Preview of the Design implemented 👇

screen shot 2018-11-22 at 10 42 03 pm

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Hi, good work. Please add conditions to optional fields... If or not they are provided and then only show them. In case issuer has not put the field still the labels would be shown which would be incorrect. You may use *ngIf here

**Comment by saivittalb** [comment]
> Hi, good work. Please add conditions to optional fields... If or not they are provided and then only show them. In case issuer has not put the field still the labels would be shown which would be incorrect. You may use *ngIf here

I added the ```ngIf``` statement in the ```certificate.component.html file```..... Please check and if anything is required to change, please let me know 😃

**Comment by nikitadhiman** [comment]
But you have not set value of ifFieldChosen anywhere

**Comment by saivittalb** [comment]
I initialized ```ifFieldChosen``` field to ```true``` in ```certificate.component.ts```

**Comment by nikitadhiman** [comment]
@saivittalb can you please put your template files under some templates/{some folder}/your files. Would like to merge this

**Comment by saivittalb** [comment]
> @saivittalb can you please put your template files under some templates/{some folder}/your files. Would like to merge this

Done 👍 Had to create a file with my name as file name with 'certificate' is causing conflicts!

**Pull request merged**
