### PR TITLE
Added Certificate template.

### PR DESCRIPTION
**Pull request by crowded-geek**
Screenshot:
image

### CODE REVIEW

**Comment by crowded-geek** [comment]
@prithaupadhyay, Thanks!

**Comment by nikitadhiman** [comment]
@crowded-geek can you please change your component name, we would like to merge this. Instead of certificate, you can name it something else

**Comment by crowded-geek** [comment]
Sure @nikitadhiman

**Comment by crowded-geek** [comment]
@nikitadhiman Done

**Comment by nikitadhiman** [comment]
And one folder will contain only one template

**Comment by crowded-geek** [comment]
Done

**Comment by prithaupadhyay** [comment]
@crowded-geek we are considering your PR for merge. Please have a look at the other merged certificate templates and create a separate certificate-gci18.component.css file. An HTML file is not expected to contain any styling.

**Comment by crowded-geek** [comment]
@prithaupadhyay Sure will fix it close this and raise a new PR today.

**Comment by prithaupadhyay** [comment]
@crowded-geek Okay. Make sure you close this PR before raising a new one.

**Comment by crowded-geek** [comment]
Okay... Doing so.

**Comment by crowded-geek** [comment]
@prithaupadhyay https://github.com/JBossOutreach/certificate-generator-front/pull/222

**Pull request closed without merging**
