### PR TITLE
Navbar added :cheers:

### PR DESCRIPTION
**Pull request by Ananthavijay**
Task link - https://codein.withgoogle.com/dashboard/task-instances/6309336478384128/

Changes : 

Before clicking hamburger icon : 

screenshot 35

After clicking : 

updated:
screenshot 37

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Please update screenshots too

**Comment by Ananthavijay** [comment]
done @nikitadhiman

**Comment by nikitadhiman** [comment]
Closing this for now

**Comment by nikitadhiman** [comment]
@Ananthavijay , this is being considered for merge. Please align the button for sidebar with the title. Currently, it is seen a bit lower than title.

**Pull request closed without merging**
