### PR TITLE
Generating Single Certificate

### PR DESCRIPTION
**Pull request by ant159**
Do I have to change anything?
taskfinal

### CODE REVIEW

**Comment by nikitadhiman** [comment]
@ant159 good job, but you haven't included the field for certificate template i.e which template would be used for certificate. Please do that

**Comment by ant159** [comment]
@nikitadhiman  I included it in the preview button. When the user wants to preview the certificate he will have to choose from templates... 
Should I change it ?

**Comment by ant159** [comment]
@nikitadhiman  Done...

**Comment by prithaupadhyay** [comment]
Thank You @ant159 . We'll continue with the PR #192

**Pull request closed without merging**
