### PR TITLE
Added the Logo resources in certificate-generator-front

### PR DESCRIPTION
**Pull request by RaghavAwasthi**
# Added logo 

This pull request adds the Logo for the JBoss Repository "certificate-generator-front". 

The Logo resources are placed inside the logo folder in the root of repository.
There are additional mipmap folders which contain images of various densities for different devices.
* mipmap-mdpi
* mipmap-hdpi
* mipmap-xhdpi
* mipmap-xxhdpi
* mipmap-xxxhdpi

 ## Screenshot
web_hi_res_512

### CODE REVIEW

**Comment by nikitadhiman** [comment]
@divyanshkul @RaghavAwasthi @prithaupadhyay  and others what do you think of this as a logo?

**Comment by prithaupadhyay** [comment]
@nikitadhiman The logo looks really good. We can just improve the badge a bit like the orange colour in the middle and rather than having a vertical section for the badge, we can have 2 flaps. Else looks good to me.

**Comment by prithaupadhyay** [comment]
@nikitadhiman The logo looks really good. We can just improve the badge a bit like the orange colour in the middle and rather than having a vertical section for the badge, we can have 2 flaps. Else looks good to me.

**Comment by nikitadhiman** [comment]
@RaghavAwasthi please make the suggested changes.

**Comment by divyanshkul** [comment]
Nice work! @RaghavAwasthi 
yes, the orange ribbon colour looks a bit off right now. You should change it to something that suits the background.
Keep it up! 🎉

**Comment by RaghavAwasthi** [comment]
Okay @nikitadhiman @divyanshkul @prithaupadhyay  I will update them. Give me some time by today evening i will get it done 😃

**Comment by RaghavAwasthi** [comment]
Hey @nikitadhiman @divyanshkul @prithaupadhyay  I have updated the new logos. Sorry for not squashing the commits . I remembered about squashing after i had pushed the commit.

 The new logo is attached below
web_hi_res_512
 * I have added a .svg file to provide additional functionalities.

**Comment by RaghavAwasthi** [comment]
I have squashed the commits now

**Comment by prithaupadhyay** [comment]
@RaghavAwasthi  Great efforts Raghav. Just one suggestion. I will be great if you can reduce the angle between the 2 flaps and also please do something for the inner circle color shade or shape.
The angle between the flaps should be something similar to this image.
image

**Comment by RaghavAwasthi** [comment]
Okay @prithaupadhyay I will do it

**Comment by nikitadhiman** [comment]
closing this for now

**Pull request closed without merging**
