### PR TITLE
Wireframe - Signup

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Wireframe for Login Page
* Made this PR in reference to #85 
* [View Repo](https://github.com/sidhyatikku/certificate-generator-front/tree/loginfram)

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@nikitadhiman Please review the PR

**Comment by sidhyatikku** [comment]
@nikitadhiman done that as well 👍

**Comment by nikitadhiman** [comment]
Also, please save the file in assets/ folder and in readme give link to that file. This is ready to merge...great job! Let me know when done

**Comment by sidhyatikku** [comment]
The signup wireframe is already in the `src/assets` and README.MD already contains the link to the wireframe.

**Comment by nikitadhiman** [comment]
Readme contains link to your repo

**Comment by sidhyatikku** [comment]
@nikitadhiman Done 👍

**Pull request merged**
