### PR TITLE
Wireframes

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Wireframe for Dashboard of Certificate Issuer in Certificate Generator. - JBoss Community
* Made this wireframe on Adobe Illustrator
* Strictly follows material design guidelines
* Added all the images in README.MD
* Source file has been uploaded to GCI website
* Previous commits #35 #38 #44 #45 
* [View Repo](https://github.com/sidhyatikku/certificate-generator-front/tree/wireframs)

### CODE REVIEW

**Comment by nikitadhiman** [comment]
And what all actions can be taken against selected certificates by the organization? Is that column compulsory?

**Comment by sidhyatikku** [comment]
The issuer can export selected certificates, import user data, email certificates directly to receivers or even download all as zip.

**Comment by nikitadhiman** [comment]
Great!

**Comment by nikitadhiman** [comment]
@sidhyatikku , would you be able to start html coding for login page? We have backend services ready to start testing user login

**Comment by nikitadhiman** [comment]
@Khukhuna please have a look at this, if you can start html coding for login page.

**Comment by Khukhuna** [comment]
Wow this UI is amazing :fire:

**Comment by nikitadhiman** [comment]
> Wow this UI is amazing

If possible, please take this up on priority coz we are doing well in this project, thanks to all you guys

**Comment by nikitadhiman** [comment]
@sidhyatikku Can you also make a separate PR including only login page, so that we can merge that

**Comment by sidhyatikku** [comment]
Okay, I will make a PR shortly.

**Comment by nikitadhiman** [comment]
closing this due to conflicts. @sidhyatikku please send PR for each individual design

**Comment by sidhyatikku** [comment]
@nikitadhiman 👍

**Pull request closed without merging**
