### PR TITLE
certifate templete

### PR DESCRIPTION
**Pull request by moodiabdoul**
this is my preview
screenshot_2018-11-26

### CODE REVIEW

**Comment by prithaupadhyay** [comment]
@moodiabdoul  We are considering your template for merge. There is an existing folder named basic inside the templates folder, please do create a separate folder with some other name. You can have a look at the existing merged Certificate templates in the template folder. You should have .component.spec.ts and .component.ts files along with the HTML and CSS files.

**Comment by nikitadhiman** [comment]
Hi, please rename your template as we already have a template with name basic

**Comment by nikitadhiman** [comment]
also resolve the conflicts

**Comment by nikitadhiman** [comment]
No response, hence closing this for now

**Pull request closed without merging**
