### PR TITLE
GCI 2018: Created basic certificate template

### PR DESCRIPTION
**Pull request by bartekpacia**
# Overview
I've added basic certificate template. This is my first contact with Angular in my life, I was worried about it but it looks quite amazing 👏 

# Task
[Basic Certificate Template](https://codein.withgoogle.com/dashboard/task-instances/5017784275697664/)

# Graphics
cert-gen-front-template

### CODE REVIEW

**Comment by bartekpacia** [comment]
I've fixed it :)

**Comment by nikitadhiman** [comment]
One question, what's the thing you are fixing for #180?

**Comment by bartekpacia** [comment]
Oh, it's a mistake. I thought #180 is an issue but it's a PR.
Deleted.

**Comment by nikitadhiman** [comment]
Hi, thanks for your work. This would be considered for merge incase we need more templates

**Pull request closed without merging**
