### PR TITLE
Adding Optional fields to the Template

### PR DESCRIPTION
**Pull request by ant159**
Task: https://codein.withgoogle.com/tasks/5380860145565696/?sp-search=adding%20op
I used the basic template that I've already done for another task. @nikitadhiman  Is it okay?
v

### CODE REVIEW

**Comment by nikitadhiman** [comment]
What the optional field have you included?

**Comment by ant159** [comment]
@nikitadhiman In this example from the gif, I included 'valid till' in the right corner(up) of the certificate

**Comment by ant159** [comment]
@nikitadhiman  I think I did a mistake at the placeholder of the third input...it should be margin bottom😅
I'll change it now

**Comment by nikitadhiman** [comment]
Thanks for your work, closing this for now

**Pull request closed without merging**
