### PR TITLE
GCI 2018 Generating Certificate

### PR DESCRIPTION
**Pull request by IlyaMaier**
What's new:
- Certificate's template
- Form with an immediate preview and validations

Screenshots:

### CODE REVIEW

**Comment by IlyaMaier** [comment]
Hi! If you're talking about min length of the fields, or pattern to validate them, than i can do it in html file. If not, i don't see any purpose to use template driven or reactive forms... I think it's easier to do it in html file, 'cause it doesn't need any extra imports, or extra lines of code, it's just attribute and it's done.

**Comment by nikitadhiman** [comment]
I totally agree, but we are following a standard across the application. It won't be feasible to use something else in some part of application and something different in different. Let's maintain a standard so that it would be easier to do additional code later on

**Comment by IlyaMaier** [comment]
OK. I agree with you, that it'll better, but I've tried 50 times doing that, and I got error everytime, maybe it's because I use WebStorm and not VS, I know it sounds crazy, but doing exactly the same things as in guides I got errors.

**Comment by IlyaMaier** [comment]
Oops. I've squashed too much commits. Should i create a new PR?

**Pull request closed without merging**
