### PR TITLE
Wireframe for login page

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Wireframe for login page of Certificate Generator - JBoss Community
* Made using Adobe Illustrator 
* Source File has been submitted with GCI Website
* [Task Link](https://codein.withgoogle.com/dashboard/task-instances/5902087108952064/)

wire_login

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@nikitadhiman @sukhbir-singh here it is

**Comment by pabisovsky** [comment]
very good

today i try do this task :)

**Comment by sukhbir-singh** [comment]
Thanks for pull request @sidhyatikku !! great work on this...!

**Comment by sidhyatikku** [comment]
@sukhbir-singh no problem. Please do review the task! 😅

**Pull request closed without merging**
