### PR TITLE
Updated & Removed unused css classes

### PR DESCRIPTION
**Pull request by Khukhuna**
There's no difference in look, except restored responsivity (on mobile content dissapears & only login form is visible, mobile [before](https://user-images.githubusercontent.com/37747169/49020426-d891c900-f1a9-11e8-9d77-978881f6ef30.png) / [after](https://user-images.githubusercontent.com/37747169/49020432-daf42300-f1a9-11e8-971a-a1465df2a734.png) )

also one question: should we vertically center content & login form for better ux?

### CODE REVIEW

**Comment by nikitadhiman** [comment]
Hi, if possible..at any given point of time ..the entire content should fit within the screen, there should not be a need of vertical scroll bar. Does this updates satisfy the condition?

**Comment by Khukhuna** [comment]
I'm on it.
one more question: we are not displaying navbar on login page, right?

**Comment by nikitadhiman** [comment]
No, because we are already providing those options in the page itself

**Comment by nikitadhiman** [comment]
@Khukhuna did you get chance to update this or are you done?

**Pull request merged**
