### PR TITLE
Wireframe Dashboard for Issuer & Student

### PR DESCRIPTION
**Pull request by sidhyatikku**
##### Dashboard for Issuer & Student

dash_ment
dashstud

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@nikitadhiman PR for the requested wireframes

**Comment by nikitadhiman** [comment]
Buttons should be one top, right? For issuer dashboard

**Comment by sidhyatikku** [comment]
@nikitadhiman I believe the buttons should be below, as I think the issuer should first be able to check what students are selected and then perform any actions. If you want, I can bring the buttons above the data.

**Comment by nikitadhiman** [comment]
Just in case if the list is really long....will the issuer scroll until
last to see the button?

On Dec 5, 2018 11:14 PM, "Sidhya Tikku" <notifications@github.com> wrote:

@nikitadhiman <https://github.com/nikitadhiman> I believe the buttons
should be below, as I think the issuer should first be able to check what
students are selected and then perform any actions. If you want, I can
bring the buttons above the data.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JBossOutreach/certificate-generator-front/pull/209#issuecomment-444576670>,
or mute the thread

**Comment by sidhyatikku** [comment]
@nikitadhiman In that case I would agree the top button makes more sense. Lemme do that ASAP.

**Comment by sidhyatikku** [comment]
Making a fresh new PR

**Pull request closed without merging**
